chiffre=int(input("table de quel chiffre?"))
print(chiffre*1)
print(chiffre*2)
print(chiffre*3)
print(chiffre*4)
print(chiffre*5)
print(chiffre*6)
print(chiffre*7)
print(chiffre*8)
print(chiffre*9)
print(chiffre*10)
